#!/usr/bin/env bash
#
# provenance-selftest.sh — exercises scripts/make-provenance.sh, scripts/deploy.sh's
# sidecar transport, and scripts/drift-check.sh's sidecar report, against a throwaway
# fixture git repository, a stub `ssh` first on PATH (for deploy.sh, as
# deploy-selftest.sh does), and a local static server bound to 127.0.0.1 driven from a
# control directory (for drift-check.sh, as drift-check-selftest.sh does). Contacts no
# host other than 127.0.0.1.
#
# Cases (see docs/stories/INFRA/INFRA-008.md § Tests):
#   1.  generate                        — exit 0; one JSON object; fixture HEAD sha;
#                                          both bundle sha256 values match; both
#                                          timestamps in ...Z form
#   2.  generate, untracked bundle      — exit 5; names the bundle and the ref; no
#                                          partial JSON on stdout
#   3.  generate, usage error           — exit 64, not 2 (CER-015)
#   3a. generate, --ref class (INFRA-017/CER-033) — `--ref 'q"b'` (a real branch) and
#                                          `--ref -x` each exit 64 with empty stdout;
#                                          `--ref rel/a-1.b_2` exits 0 and json.load of
#                                          the output yields that repo_ref
#   3b. INFRA-022 (CER-063, MOVE), on annotated fixture tags rel-fixture (at HEAD),
#       tree-fixture (a tag of HEAD's tree) and rel-move (at HEAD):
#       a. --ref rel-fixture               — exit 0; json.load gives repo_commit = the
#                                          commit, repo_ref = rel-fixture, the commit's
#                                          date; the tag object's short sha absent
#                                          (vacuity guard: tag object sha != commit sha)
#       b. --ref tree-fixture              — exit 5, empty stdout, "does not name a commit"
#       c. MOVE: --ref rel-move, with a git wrapper first on PATH for this run only that
#          re-points rel-move at COMMIT1 straight after the first git call naming it —
#                                          exit 0; repo_commit and the index.html hash
#                                          are HEAD's (vacuity guard: the seam fired and
#                                          rel-move^{commit} is now COMMIT1)
#       d. MOVE: --ref rel-fixture --commit COMMIT1 — records COMMIT1, its index.html hash
#                                          and date under repo_ref rel-fixture;
#                                          --commit not-a-sha exits 64, "--commit takes"
#   4.  deploy writes sidecar           — exit 0; site-provenance.json present in the
#                                          target with the generated bytes; repo_commit
#                                          is the fixture HEAD; success block names it
#   5.  bundles untouched by deploy     — same run; both fixture bundles in the target
#                                          are byte-identical to git show HEAD:<bundle>;
#                                          the sidecar bytes appear in no bundle
#   6.  sidecar written last            — stub ssh fails the copy step for
#                                          gap-handoff.html; non-zero exit;
#                                          site-provenance.json absent from the target
#   7.  dry run                         — exit 0; JSON printed; stub-ssh marker absent
#   8.  drift check, honest sidecar     — exit 0; claim line names the sidecar's
#                                          commit and is labelled a claim
#   9.  drift check, lying sidecar      — exit 6; disagreement reported per bundle
#   10. lying sidecar cannot rescue drift — exit 3, not 0 and not 6
#   11. sidecar absent                  — exit 0; one line says the sidecar is absent
#                                          and the decision does not depend on it
#
# Exits non-zero if any case fails.

set -euo pipefail

REPO_ROOT="$(git -C "$(dirname "${BASH_SOURCE[0]}")/.." rev-parse --show-toplevel)"
MAKE_PROVENANCE_SH="$REPO_ROOT/scripts/make-provenance.sh"
DEPLOY_SH="$REPO_ROOT/scripts/deploy.sh"
DRIFT_CHECK_SH="$REPO_ROOT/scripts/drift-check.sh"

WORK_DIR="$(mktemp -d)"
SERVER_PID=""
cleanup() {
  if [ -n "$SERVER_PID" ] && kill -0 "$SERVER_PID" 2>/dev/null; then
    kill "$SERVER_PID" 2>/dev/null || true
    wait "$SERVER_PID" 2>/dev/null || true
  fi
  rm -rf "$WORK_DIR"
}
trap cleanup EXIT

FIXTURE_REPO="$WORK_DIR/fixture-repo"
FIXTURE_TARGET="$WORK_DIR/fixture-target"
STUB_BIN="$WORK_DIR/stub-bin"
SSH_MARKER="$WORK_DIR/ssh-marker"
FAIL_GAP_COPY="$WORK_DIR/fail-gap-copy-flag"
SERVE_DIR="$WORK_DIR/serve-dir"
CONTROL_DIR="$WORK_DIR/control-dir"
REQUEST_LOG="$WORK_DIR/request-log"
SERVER_SCRIPT="$WORK_DIR/fixture-server.py"

FAILURES=0
PASS_COUNT=0
ALL_OUTPUT="$WORK_DIR/all-output"
: > "$ALL_OUTPUT"

report() {
  local name="$1" ok="$2" detail="$3"
  if [ "$ok" -eq 0 ]; then
    echo "PASS: $name"
    PASS_COUNT=$((PASS_COUNT + 1))
  else
    echo "FAIL: $name — $detail"
    FAILURES=$((FAILURES + 1))
  fi
}

capture() {
  # Appends a labelled case's combined stdout+stderr to $ALL_OUTPUT for the hygiene
  # greps in the story's § Tests to run against.
  local label="$1" text="$2"
  {
    echo "--- ${label} ---"
    printf '%s\n' "$text"
  } >> "$ALL_OUTPUT"
}

# =====================================================================================
# Fixture git repo: two commits touching index.html, one HEAD state for gap-handoff.
# =====================================================================================
mkdir -p "$FIXTURE_REPO"
git -C "$FIXTURE_REPO" init -q
git -C "$FIXTURE_REPO" config user.email "selftest@example.invalid"
git -C "$FIXTURE_REPO" config user.name "provenance-selftest"

printf 'fixture index v1\n' > "$FIXTURE_REPO/index.html"
printf 'fixture gap-handoff bundle\n' > "$FIXTURE_REPO/gap-handoff.html"
git -C "$FIXTURE_REPO" add index.html gap-handoff.html
git -C "$FIXTURE_REPO" commit -q -m "fixture: initial bundles"
COMMIT1="$(git -C "$FIXTURE_REPO" rev-parse HEAD)"

printf 'fixture index v2\n' > "$FIXTURE_REPO/index.html"
git -C "$FIXTURE_REPO" add index.html
git -C "$FIXTURE_REPO" commit -q -m "fixture: index v2"

HEAD_SHA="$(git -C "$FIXTURE_REPO" rev-parse HEAD)"
HEAD_INDEX_SHA256="$(git -C "$FIXTURE_REPO" show HEAD:index.html | sha256sum | cut -d' ' -f1)"
HEAD_GAP_SHA256="$(git -C "$FIXTURE_REPO" show HEAD:gap-handoff.html | sha256sum | cut -d' ' -f1)"
COMMIT1_INDEX_SHA256="$(git -C "$FIXTURE_REPO" show "${COMMIT1}:index.html" | sha256sum | cut -d' ' -f1)"

run_make_provenance() {
  ( cd "$FIXTURE_REPO" && "$MAKE_PROVENANCE_SH" "$@" )
}

# =====================================================================================
# Case 1: generate
# =====================================================================================
set +e
out_case1="$(run_make_provenance 2>&1)"
status_case1=$?
set -e
capture "case1 generate" "$out_case1"

ok=0
detail=""
if [ "$status_case1" -ne 0 ]; then
  ok=1; detail="expected exit 0, got $status_case1: $out_case1"
elif [ "$(printf '%s' "$out_case1" | grep -c '^{$')" -ne 1 ]; then
  ok=1; detail="stdout is not exactly one JSON object (opening brace count != 1)"
elif ! printf '%s' "$out_case1" | grep -q "\"repo_commit\": \"${HEAD_SHA}\""; then
  ok=1; detail="repo_commit does not carry the fixture HEAD sha ($HEAD_SHA)"
elif ! printf '%s' "$out_case1" | grep -q "\"index.html\": \"${HEAD_INDEX_SHA256}\""; then
  ok=1; detail="index.html sha256 does not match git show HEAD:index.html | sha256sum"
elif ! printf '%s' "$out_case1" | grep -q "\"gap-handoff.html\": \"${HEAD_GAP_SHA256}\""; then
  ok=1; detail="gap-handoff.html sha256 does not match git show HEAD:gap-handoff.html | sha256sum"
elif ! printf '%s' "$out_case1" | grep -Eq '"repo_commit_date": "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z"'; then
  ok=1; detail="repo_commit_date not in ...Z form"
elif ! printf '%s' "$out_case1" | grep -Eq '"deployed_at": "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z"'; then
  ok=1; detail="deployed_at not in ...Z form"
fi
report "generate (exit 0, one JSON object, fixture HEAD sha, both bundle sha256, ...Z timestamps)" "$ok" "$detail"

# =====================================================================================
# Case 2: generate, untracked bundle
# =====================================================================================
git -C "$FIXTURE_REPO" rm -q gap-handoff.html
git -C "$FIXTURE_REPO" commit -q -m "fixture: remove gap-handoff.html"
UNTRACKED_REF="$(git -C "$FIXTURE_REPO" rev-parse HEAD)"

set +e
out_case2="$(run_make_provenance 2>&1)"
status_case2=$?
set -e
capture "case2 generate untracked bundle" "$out_case2"

ok=0
detail=""
if [ "$status_case2" -ne 5 ]; then
  ok=1; detail="expected exit 5, got $status_case2: $out_case2"
elif ! printf '%s' "$out_case2" | grep -q "gap-handoff.html"; then
  ok=1; detail="message did not name the untracked bundle"
elif ! printf '%s' "$out_case2" | grep -q "HEAD"; then
  ok=1; detail="message did not name the ref"
elif printf '%s' "$out_case2" | grep -q '^{$'; then
  ok=1; detail="partial JSON was printed to stdout despite the failure"
fi
report "generate, untracked bundle (exit 5, names bundle + ref, no partial JSON)" "$ok" "$detail"

# Restore the fixture repo to its two-bundle HEAD for the remaining cases.
git -C "$FIXTURE_REPO" reset -q --hard "$HEAD_SHA"

# =====================================================================================
# Case 3: generate, usage error
# =====================================================================================
set +e
out_case3="$(run_make_provenance --nonsense-flag 2>&1)"
status_case3=$?
set -e
capture "case3 generate usage error" "$out_case3"

ok=0
detail=""
if [ "$status_case3" -ne 64 ]; then
  ok=1; detail="expected exit 64, got $status_case3: $out_case3"
elif [ "$status_case3" -eq 2 ]; then
  ok=1; detail="usage error shares exit code 2 (CER-015)"
fi
report "generate, usage error (exit 64, not 2 — CER-015)" "$ok" "$detail"

# =====================================================================================
# Case 3a: generate, --ref class (INFRA-017/CER-033) — a ref outside REF_RE is refused
# before anything is printed, so the sidecar is always valid JSON. q"b is a real branch,
# so without the check it would resolve and be written into repo_ref unescaped.
# =====================================================================================
git -C "$FIXTURE_REPO" branch 'q"b'
git -C "$FIXTURE_REPO" branch 'rel/a-1.b_2'

ok=0
detail=""
for bad_ref in 'q"b' '-x'; do
  set +e
  bad_stdout="$(run_make_provenance --ref "$bad_ref" 2>/dev/null)"
  bad_status=$?
  set -e
  if [ "$bad_status" -ne 64 ]; then
    ok=1; detail="--ref $bad_ref: expected exit 64, got $bad_status"; break
  elif [ -n "$bad_stdout" ]; then
    ok=1; detail="--ref $bad_ref: stdout was not empty"; break
  fi
done
report "generate, --ref outside the class: q\"b and -x (exit 64, empty stdout) INFRA-017/CER-033" "$ok" "$detail"

set +e
good_stdout="$(run_make_provenance --ref 'rel/a-1.b_2' 2>/dev/null)"
good_status=$?
set -e
capture "case3a generate --ref rel/a-1.b_2" "$good_stdout"
ok=0
detail=""
if [ "$good_status" -ne 0 ]; then
  ok=1; detail="expected exit 0, got $good_status"
elif ! printf '%s' "$good_stdout" | python3 -c 'import json, sys; sys.exit(0 if json.load(sys.stdin)["repo_ref"] == "rel/a-1.b_2" else 1)' 2>/dev/null; then
  ok=1; detail="output does not json.load with repo_ref == rel/a-1.b_2: $good_stdout"
fi
report "generate, --ref rel/a-1.b_2 (exit 0, json.load gives that repo_ref) INFRA-017/CER-033" "$ok" "$detail"

# =====================================================================================
# INFRA-022 fixtures: annotated tags, and the moving-ref seam.
#   rel-fixture  — annotated tag at HEAD
#   tree-fixture — annotated tag of HEAD's tree (names no commit)
#   rel-move     — annotated tag at HEAD, re-pointed mid-run by the git wrapper below
# =====================================================================================
git -C "$FIXTURE_REPO" tag -a -m "fixture: release tag" rel-fixture "$HEAD_SHA"
git -C "$FIXTURE_REPO" tag -a -m "fixture: tag of a tree" tree-fixture "${HEAD_SHA}^{tree}"
git -C "$FIXTURE_REPO" tag -a -m "fixture: moving tag" rel-move "$HEAD_SHA"
REL_TAG_OBJ="$(git -C "$FIXTURE_REPO" rev-parse rel-fixture)"
REL_TAG_OBJ_SHORT="$(git -C "$FIXTURE_REPO" rev-parse --short rel-fixture)"
HEAD_DATE="$(TZ=UTC git -C "$FIXTURE_REPO" log -1 --format=%cd --date=format-local:%Y-%m-%dT%H:%M:%SZ "$HEAD_SHA")"
COMMIT1_DATE="$(TZ=UTC git -C "$FIXTURE_REPO" log -1 --format=%cd --date=format-local:%Y-%m-%dT%H:%M:%SZ "$COMMIT1")"

# The moving-ref seam (INFRA-022/MOVE). A `git` wrapper that runs the real git (its path
# captured here, before the wrapper exists). On the first call whose arguments name
# rel-move while $MOVE_TRIGGER exists, it deletes the trigger, runs that call, then
# re-points rel-move at $MOVE_TO with `tag -f -a`, and returns the call's own status.
# It is put first on PATH for the one MOVE run only, inside a subshell; never exported.
REAL_GIT="$(command -v git)"
GIT_WRAP_DIR="$WORK_DIR/git-wrap"
MOVE_TRIGGER="$WORK_DIR/move-trigger"
mkdir -p "$GIT_WRAP_DIR"
cat > "$GIT_WRAP_DIR/git" <<WRAP
#!/usr/bin/env bash
names_move=0
for a in "\$@"; do
  case "\$a" in *rel-move*) names_move=1 ;; esac
done
if [ "\$names_move" -eq 1 ] && [ -f "$MOVE_TRIGGER" ]; then
  rm -f "$MOVE_TRIGGER"
  status=0
  "$REAL_GIT" "\$@" || status=\$?
  "$REAL_GIT" tag -f -a -m "fixture: moved mid-run" rel-move "\$MOVE_TO" >/dev/null 2>&1
  exit "\$status"
fi
exec "$REAL_GIT" "\$@"
WRAP
chmod +x "$GIT_WRAP_DIR/git"

json_field() {  # $1 field; reads JSON on stdin; prints the field or nothing
  python3 -c 'import json, sys; print(json.load(sys.stdin)[sys.argv[1]])' "$1" 2>/dev/null || true
}
json_bundle() {  # $1 bundle name; reads JSON on stdin
  python3 -c 'import json, sys; print(json.load(sys.stdin)["bundles"][sys.argv[1]])' "$1" 2>/dev/null || true
}

# --- INFRA-022 case a: an annotated tag is recorded as its commit --------------------
set +e
tag_stdout="$(run_make_provenance --ref rel-fixture 2>/dev/null)"
tag_status=$?
set -e
capture "INFRA-022 generate --ref rel-fixture" "$tag_stdout"
ok=0
detail=""
if [ "$REL_TAG_OBJ" = "$HEAD_SHA" ]; then
  ok=1; detail="precondition: rel-fixture's tag object sha equals its commit, so the case is vacuous"
elif [ "$tag_status" -ne 0 ]; then
  ok=1; detail="expected exit 0, got $tag_status"
elif [ "$(printf '%s' "$tag_stdout" | json_field repo_commit)" != "$HEAD_SHA" ]; then
  ok=1; detail="repo_commit is not the commit rel-fixture points to ($HEAD_SHA): $tag_stdout"
elif [ "$(printf '%s' "$tag_stdout" | json_field repo_ref)" != "rel-fixture" ]; then
  ok=1; detail="repo_ref is not rel-fixture: $tag_stdout"
elif [ "$(printf '%s' "$tag_stdout" | json_field repo_commit_date)" != "$HEAD_DATE" ]; then
  ok=1; detail="repo_commit_date is not the commit's committer date ($HEAD_DATE): $tag_stdout"
elif printf '%s' "$tag_stdout" | grep -qF "$REL_TAG_OBJ_SHORT"; then
  ok=1; detail="the tag object's sha ($REL_TAG_OBJ_SHORT) appears in the output: $tag_stdout"
fi
report "generate, --ref an annotated tag (exit 0, repo_commit is its commit, repo_ref the tag, the commit's date, no tag object sha) INFRA-022/CER-063" "$ok" "$detail"

# --- INFRA-022 case b: a ref that names no commit is refused -------------------------
set +e
tree_stdout="$(run_make_provenance --ref tree-fixture 2>/dev/null)"
tree_status=$?
tree_stderr="$(run_make_provenance --ref tree-fixture 2>&1 >/dev/null)"
set -e
ok=0
detail=""
if [ "$(git -C "$FIXTURE_REPO" cat-file -t 'tree-fixture^{}' 2>/dev/null)" != "tree" ]; then
  ok=1; detail="precondition: tree-fixture does not peel to a tree, so the case is vacuous"
elif [ "$tree_status" -ne 5 ]; then
  ok=1; detail="expected exit 5, got $tree_status: $tree_stdout"
elif [ -n "$tree_stdout" ]; then
  ok=1; detail="stdout was not empty: $tree_stdout"
elif ! printf '%s' "$tree_stderr" | grep -qF 'does not name a commit'; then
  ok=1; detail="the refusal does not say the ref names no commit: $tree_stderr"
fi
report "generate, --ref a tag of a tree (exit 5, empty stdout, does not name a commit) INFRA-022/CER-063" "$ok" "$detail"

# --- INFRA-022 case c: a ref moved mid-run cannot mix commits ------------------------
git -C "$FIXTURE_REPO" tag -f -a -m "fixture: moving tag" rel-move "$HEAD_SHA" >/dev/null
: > "$MOVE_TRIGGER"
set +e
move_stdout="$( export PATH="$GIT_WRAP_DIR:$PATH"; export MOVE_TO="$COMMIT1"; run_make_provenance --ref rel-move 2>/dev/null )"
move_status=$?
set -e
capture "INFRA-022 generate --ref rel-move (moved mid-run)" "$move_stdout"
moved_to="$(git -C "$FIXTURE_REPO" rev-parse -q --verify 'rel-move^{commit}' 2>/dev/null || true)"
ok=0
detail=""
if [ -f "$MOVE_TRIGGER" ]; then
  ok=1; detail="precondition: the seam never fired (no git call named rel-move)"
elif [ "$moved_to" != "$COMMIT1" ]; then
  ok=1; detail="precondition: rel-move^{commit} is $moved_to after the run, not the move target $COMMIT1"
elif [ "$move_status" -ne 0 ]; then
  ok=1; detail="expected exit 0, got $move_status: $move_stdout"
elif [ "$(printf '%s' "$move_stdout" | json_field repo_commit)" != "$HEAD_SHA" ]; then
  ok=1; detail="repo_commit is not the commit rel-move named when resolved ($HEAD_SHA): $move_stdout"
elif [ "$(printf '%s' "$move_stdout" | json_bundle index.html)" != "$HEAD_INDEX_SHA256" ]; then
  ok=1; detail="the index.html hash is not HEAD's — the run read a second commit: $move_stdout"
elif [ "$(printf '%s' "$move_stdout" | json_field repo_ref)" != "rel-move" ]; then
  ok=1; detail="repo_ref is not rel-move: $move_stdout"
fi
rm -f "$MOVE_TRIGGER"
report "generate, --ref moved to another commit straight after its first read (exit 0, repo_commit and index.html hash are the resolved commit's) INFRA-022/MOVE" "$ok" "$detail"

# --- INFRA-022 case d: --commit is the seam; it records that commit ------------------
set +e
pin_stdout="$(run_make_provenance --ref rel-fixture --commit "$COMMIT1" 2>/dev/null)"
pin_status=$?
badpin_stdout="$(run_make_provenance --ref rel-fixture --commit not-a-sha 2>/dev/null)"
badpin_status=$?
badpin_stderr="$(run_make_provenance --ref rel-fixture --commit not-a-sha 2>&1 >/dev/null)"
set -e
capture "INFRA-022 generate --ref rel-fixture --commit COMMIT1" "$pin_stdout"
ok=0
detail=""
if [ "$COMMIT1" = "$HEAD_SHA" ]; then
  ok=1; detail="precondition: COMMIT1 equals HEAD, so the case cannot tell --commit from --ref"
elif [ "$pin_status" -ne 0 ]; then
  ok=1; detail="expected exit 0, got $pin_status"
elif [ "$(printf '%s' "$pin_stdout" | json_field repo_commit)" != "$COMMIT1" ]; then
  ok=1; detail="repo_commit is not the --commit sha ($COMMIT1): $pin_stdout"
elif [ "$(printf '%s' "$pin_stdout" | json_bundle index.html)" != "$COMMIT1_INDEX_SHA256" ]; then
  ok=1; detail="the index.html hash is not COMMIT1's: $pin_stdout"
elif [ "$(printf '%s' "$pin_stdout" | json_field repo_commit_date)" != "$COMMIT1_DATE" ]; then
  ok=1; detail="repo_commit_date is not COMMIT1's committer date: $pin_stdout"
elif [ "$(printf '%s' "$pin_stdout" | json_field repo_ref)" != "rel-fixture" ]; then
  ok=1; detail="repo_ref is not rel-fixture: $pin_stdout"
elif [ "$badpin_status" -ne 64 ]; then
  ok=1; detail="--commit not-a-sha: expected exit 64, got $badpin_status"
elif [ -n "$badpin_stdout" ]; then
  ok=1; detail="--commit not-a-sha: stdout was not empty"
elif ! printf '%s' "$badpin_stderr" | grep -qF -- 'make-provenance.sh: --commit takes'; then
  ok=1; detail="--commit not-a-sha: the refusal does not begin 'make-provenance.sh: --commit takes': $badpin_stderr"
fi
report "generate, --ref rel-fixture --commit COMMIT1 (records COMMIT1, its index.html hash, repo_ref rel-fixture; --commit not-a-sha exits 64) INFRA-022/MOVE" "$ok" "$detail"

# =====================================================================================
# Build stub ssh, first on PATH, for the deploy.sh cases.
# The stub ignores its first argument (the host alias) and runs the remainder of its
# arguments with bash -c against the fixture target directory, recording invocation.
# When $FAIL_GAP_COPY exists, the copy step ("cat >") for a temp name containing
# "gap-handoff.html" fails instead of succeeding, to prove the sidecar is never
# published over a failed bundle copy.
# =====================================================================================
mkdir -p "$STUB_BIN"
cat > "$STUB_BIN/ssh" <<STUB
#!/usr/bin/env bash
echo "invoked" >> "$SSH_MARKER"
shift
cmd="\$1"
if [ -f "$FAIL_GAP_COPY" ]; then
  case "\$cmd" in
    *"gap-handoff.html"*"cat >"*|*"cat >"*"gap-handoff.html"*)
      echo "stub-ssh: simulated failure for gap-handoff.html copy" >&2
      exit 1
      ;;
  esac
fi
out="\$(bash -c "\$cmd")"
status=\$?
printf '%s\n' "\$out"
exit "\$status"
STUB
chmod +x "$STUB_BIN/ssh"

export PATH="$STUB_BIN:$PATH"
export FORQSITE_HELP_DEPLOY_HOST="fixture-host-alias"
export FORQSITE_HELP_DEPLOY_DIR="$FIXTURE_TARGET"

run_deploy() {
  ( cd "$FIXTURE_REPO" && "$DEPLOY_SH" "$@" )
}

# =====================================================================================
# Case 4 + 5: deploy writes sidecar; bundles untouched by deploy
# =====================================================================================
mkdir -p "$FIXTURE_TARGET"
rm -f "$SSH_MARKER"

set +e
out_case4="$(run_deploy 2>&1)"
status_case4=$?
set -e
capture "case4-5 deploy writes sidecar" "$out_case4"

ok=0
detail=""
if [ "$status_case4" -ne 0 ]; then
  ok=1; detail="expected exit 0, got $status_case4: $out_case4"
elif [ ! -f "$FIXTURE_TARGET/site-provenance.json" ]; then
  ok=1; detail="site-provenance.json not present in the target"
elif ! grep -q "\"repo_commit\": \"${HEAD_SHA}\"" "$FIXTURE_TARGET/site-provenance.json"; then
  ok=1; detail="target sidecar's repo_commit is not the fixture HEAD"
elif ! printf '%s' "$out_case4" | grep -q "site-provenance.json"; then
  ok=1; detail="success block did not name site-provenance.json"
fi
report "deploy writes sidecar (exit 0, sidecar present with generated bytes, success block names it)" "$ok" "$detail"

ok=0
detail=""
target_index_sha="$(sha256sum "$FIXTURE_TARGET/index.html" 2>/dev/null | cut -d' ' -f1 || true)"
target_gap_sha="$(sha256sum "$FIXTURE_TARGET/gap-handoff.html" 2>/dev/null | cut -d' ' -f1 || true)"
if [ "$target_index_sha" != "$HEAD_INDEX_SHA256" ]; then
  ok=1; detail="target index.html is not byte-identical to git show HEAD:index.html"
elif [ "$target_gap_sha" != "$HEAD_GAP_SHA256" ]; then
  ok=1; detail="target gap-handoff.html is not byte-identical to git show HEAD:gap-handoff.html"
elif [ -f "$FIXTURE_TARGET/site-provenance.json" ] && \
     grep -qF "site-provenance" "$FIXTURE_TARGET/index.html" 2>/dev/null; then
  ok=1; detail="sidecar name leaked into index.html"
elif [ -f "$FIXTURE_TARGET/site-provenance.json" ] && \
     grep -qF "site-provenance" "$FIXTURE_TARGET/gap-handoff.html" 2>/dev/null; then
  ok=1; detail="sidecar name leaked into gap-handoff.html"
elif grep -qFx "$(cat "$FIXTURE_TARGET/site-provenance.json")" "$FIXTURE_TARGET/index.html" 2>/dev/null; then
  ok=1; detail="sidecar bytes appear in index.html"
elif grep -qFx "$(cat "$FIXTURE_TARGET/site-provenance.json")" "$FIXTURE_TARGET/gap-handoff.html" 2>/dev/null; then
  ok=1; detail="sidecar bytes appear in gap-handoff.html"
fi
report "bundles untouched by deploy (byte-identical to HEAD, sidecar bytes in no bundle)" "$ok" "$detail"

# =====================================================================================
# Case 6: sidecar written last — stub ssh fails the copy step for gap-handoff.html
# =====================================================================================
rm -rf "$FIXTURE_TARGET"
mkdir -p "$FIXTURE_TARGET"
rm -f "$SSH_MARKER"
: > "$FAIL_GAP_COPY"

set +e
out_case6="$(run_deploy 2>&1)"
status_case6=$?
set -e
capture "case6 sidecar written last" "$out_case6"

rm -f "$FAIL_GAP_COPY"

ok=0
detail=""
if [ "$status_case6" -eq 0 ]; then
  ok=1; detail="expected a non-zero exit when the gap-handoff.html copy step fails, got 0"
elif [ -f "$FIXTURE_TARGET/site-provenance.json" ]; then
  ok=1; detail="site-provenance.json was published despite a failed bundle copy"
fi
report "sidecar written last (non-zero exit, site-provenance.json absent from target)" "$ok" "$detail"

# =====================================================================================
# Case 7: dry run
# =====================================================================================
rm -rf "$FIXTURE_TARGET"
mkdir -p "$FIXTURE_TARGET"
rm -f "$SSH_MARKER"

set +e
out_case7="$(run_deploy --dry-run 2>&1)"
status_case7=$?
set -e
capture "case7 dry run" "$out_case7"

ok=0
detail=""
if [ "$status_case7" -ne 0 ]; then
  ok=1; detail="expected exit 0, got $status_case7: $out_case7"
elif [ -f "$SSH_MARKER" ]; then
  ok=1; detail="stub-ssh marker file present — ssh was invoked during a dry run"
elif ! printf '%s' "$out_case7" | grep -q "\"repo_commit\": \"${HEAD_SHA}\""; then
  ok=1; detail="dry-run output did not print the generated JSON"
fi
report "dry run (exit 0, JSON printed, no ssh invoked)" "$ok" "$detail"

# =====================================================================================
# Deploy a real happy-path copy now, so the drift-check cases below have real target
# bytes and a real sidecar to serve.
# =====================================================================================
rm -rf "$FIXTURE_TARGET"
mkdir -p "$FIXTURE_TARGET"
rm -f "$SSH_MARKER"
run_deploy >/dev/null

# =====================================================================================
# Fixture static server: serves $SERVE_DIR by default, $CONTROL_DIR/override-<name>
# instead when present (so served bytes can differ from on-disk bytes), and a 404 when
# $CONTROL_DIR/404-<name> is present. As drift-check-selftest.sh's server.
# =====================================================================================
mkdir -p "$SERVE_DIR" "$CONTROL_DIR"
cp "$FIXTURE_TARGET/index.html" "$SERVE_DIR/index.html"
cp "$FIXTURE_TARGET/gap-handoff.html" "$SERVE_DIR/gap-handoff.html"
cp "$FIXTURE_TARGET/site-provenance.json" "$SERVE_DIR/site-provenance.json"

reset_control() {
  rm -f "$CONTROL_DIR"/override-* "$CONTROL_DIR"/404-* 2>/dev/null || true
  : > "$REQUEST_LOG"
}
reset_control

cat > "$SERVER_SCRIPT" <<'PYEOF'
import http.server
import os
import socketserver
import sys

SERVE_DIR, CONTROL_DIR, REQUEST_LOG, PORT = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4])


class Handler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        name = self.path.lstrip("/")
        with open(REQUEST_LOG, "a") as log:
            log.write(name + "\n")
        notfound = os.path.join(CONTROL_DIR, "404-" + name)
        if os.path.exists(notfound):
            self.send_response(404)
            self.end_headers()
            return
        override = os.path.join(CONTROL_DIR, "override-" + name)
        target = override if os.path.exists(override) else os.path.join(SERVE_DIR, name)
        if not os.path.exists(target):
            self.send_response(404)
            self.end_headers()
            return
        with open(target, "rb") as f:
            data = f.read()
        self.send_response(200)
        self.send_header("Content-Type", "application/octet-stream")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def log_message(self, format, *args):
        pass


class Server(socketserver.TCPServer):
    allow_reuse_address = True


with Server(("127.0.0.1", PORT), Handler) as httpd:
    httpd.serve_forever()
PYEOF

PORT=$(python3 -c 'import socket; s=socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()')
python3 "$SERVER_SCRIPT" "$SERVE_DIR" "$CONTROL_DIR" "$REQUEST_LOG" "$PORT" &
SERVER_PID=$!

for _ in $(seq 1 50); do
  if (exec 3<>"/dev/tcp/127.0.0.1/${PORT}") 2>/dev/null; then
    exec 3>&- 3<&-
    break
  fi
  sleep 0.1
done

FIXTURE_URL="http://127.0.0.1:${PORT}"
export FORQSITE_HELP_SITE_URL="$FIXTURE_URL"

run_drift_check() {
  ( cd "$FIXTURE_REPO" && "$DRIFT_CHECK_SH" "$@" )
}

HEAD_SHORT="$(git -C "$FIXTURE_REPO" rev-parse --short HEAD)"

# =====================================================================================
# Case 8: drift check, honest sidecar
# =====================================================================================
reset_control

set +e
out_case8="$(run_drift_check 2>&1)"
status_case8=$?
set -e
capture "case8 drift check honest sidecar" "$out_case8"

ok=0
detail=""
if [ "$status_case8" -ne 0 ]; then
  ok=1; detail="expected exit 0, got $status_case8: $out_case8"
elif ! printf '%s' "$out_case8" | grep -q "$HEAD_SHORT"; then
  ok=1; detail="claim line did not name the sidecar's commit ($HEAD_SHORT)"
elif ! printf '%s' "$out_case8" | grep -qi "claim"; then
  ok=1; detail="output did not label the sidecar's report as a claim"
fi
report "drift check, honest sidecar (exit 0, claim line names commit, labelled claim)" "$ok" "$detail"

# =====================================================================================
# Case 9: drift check, lying sidecar (claimed index.html sha256 altered)
# =====================================================================================
reset_control
python3 - "$SERVE_DIR/site-provenance.json" "$CONTROL_DIR/override-site-provenance.json" <<'PYEOF'
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
with open(src) as f:
    text = f.read()
text = re.sub(
    r'"index\.html": "[a-f0-9]{64}"',
    '"index.html": "' + ("0" * 64) + '"',
    text,
)
with open(dst, "w") as f:
    f.write(text)
PYEOF

set +e
out_case9="$(run_drift_check 2>&1)"
status_case9=$?
set -e
capture "case9 drift check lying sidecar" "$out_case9"

ok=0
detail=""
if [ "$status_case9" -ne 6 ]; then
  ok=1; detail="expected exit 6, got $status_case9: $out_case9"
elif ! printf '%s' "$out_case9" | grep -q "index.html"; then
  ok=1; detail="disagreement was not reported for index.html"
fi
report "drift check, lying sidecar (exit 6, disagreement reported per bundle)" "$ok" "$detail"

# =====================================================================================
# Case 10: lying sidecar cannot rescue drift — served index.html is an older commit's
# bytes, sidecar claims HEAD and matches nothing real.
# =====================================================================================
reset_control
printf 'fixture index v1\n' > "$CONTROL_DIR/override-index.html"
cp "$SERVE_DIR/site-provenance.json" "$CONTROL_DIR/override-site-provenance.json"

set +e
out_case10="$(run_drift_check 2>&1)"
status_case10=$?
set -e
capture "case10 lying sidecar cannot rescue drift" "$out_case10"

ok=0
detail=""
if [ "$status_case10" -ne 3 ]; then
  ok=1; detail="expected exit 3, got $status_case10: $out_case10"
elif [ "$status_case10" -eq 0 ] || [ "$status_case10" -eq 6 ]; then
  ok=1; detail="sidecar was allowed to influence the result"
fi
report "lying sidecar cannot rescue drift (exit 3, not 0, not 6)" "$ok" "$detail"

# =====================================================================================
# Case 11: sidecar absent
# =====================================================================================
reset_control
: > "$CONTROL_DIR/404-site-provenance.json"

set +e
out_case11="$(run_drift_check 2>&1)"
status_case11=$?
set -e
capture "case11 sidecar absent" "$out_case11"

ok=0
detail=""
if [ "$status_case11" -ne 0 ]; then
  ok=1; detail="expected exit 0, got $status_case11: $out_case11"
elif ! printf '%s' "$out_case11" | grep -qi "absent"; then
  ok=1; detail="output did not state the sidecar is absent"
elif ! printf '%s' "$out_case11" | grep -q "does not depend on it"; then
  ok=1; detail="output did not state the decision does not depend on it"
fi
report "sidecar absent (exit 0, one line says absent, decision does not depend on it)" "$ok" "$detail"

# =====================================================================================
echo ""
echo "provenance-selftest: $PASS_COUNT passed, $FAILURES failed"

echo ""
echo "--- captured output, all cases (for the hygiene grep) ---"
cat "$ALL_OUTPUT"
echo "--- end captured output ---"

if [ "$FAILURES" -ne 0 ]; then
  exit 1
fi
exit 0
